### PR TITLE
Generate snapshot write operations

### PR DESCRIPTION
**Pull request by bastbijl**
@gvdent @malamili

### CODE REVIEW

**Comment by carvilsi** [comment]
@bastbijl what's the difference between snapshotProject and dumpHistory?

**Comment by gvdent** [comment]
@carvilsi technically: writeHistory dumps the trackerdb info, snapshot derives from the virtuoso database. 

conceptually: writeHistory contains all history used to create the current database state, snapshot only stores the current state without any history.

**Comment by bastbijl** [comment]
@carvilsi dump history reads from the trackerdb and reproduces the whole history, snapshot creates write operations based on the content of the graph database. The minimal set of write operations to reproduce the snapshot current graph database state. So no history.

**Comment by carvilsi** [comment]
Thanks @bastbijl and @gvdent

**Pull request merged**
